# Generated by Django 2.1.3 on 2018-12-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sugestaoSimulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('respostaCerta', models.CharField(help_text='Atenção nesse campo, ele é para a resposta correta', max_length=200)),
                ('respostaErrada1', models.CharField(max_length=200)),
                ('respostaErrada2', models.CharField(max_length=200)),
                ('respostaErrada3', models.CharField(max_length=200)),
                ('respostaErrada4', models.CharField(max_length=200)),
            ],
        ),
    ]
